GET http://localhost:5000/api/v1/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWQ4MDFkZDBkYWUwZTcwMWM1YzJhYzciLCJpYXQiOjE2NDE1NDYyNTIsImV4cCI6MTY0MTU0NjI3Mn0.puwzSo55q3VKMla2bdlEGQRrXv7mMYUzWzPLKy_jDR8


###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "username": "daylamottaikhoanmoi",
    "password": "12334354"
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "username": "daylamottaikhoanmoi",
    "password": "12334354"
}

###
GET http://localhost:5000/api/v1/time/currentTime

###
POST http://localhost:5000/api/v1/time/formatTime
Content-Type: application/json

{
    "timeString" : "20220812011030",
    "format" : "YYYYMMDDHHmmss"
}